# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/vivado files/I_CHIP_2024/microblaze_ip_interface/soc.srcs/sources_1/bd/soc/ip/soc_xbar_26/soc_xbar_26.xci
# IP: The module: 'soc_xbar_26' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado files/I_CHIP_2024/microblaze_ip_interface/soc.srcs/sources_1/bd/soc/ip/soc_xbar_26/soc_xbar_26_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_xbar_26'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/vivado files/I_CHIP_2024/microblaze_ip_interface/soc.srcs/sources_1/bd/soc/ip/soc_xbar_26/soc_xbar_26.xci
# IP: The module: 'soc_xbar_26' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado files/I_CHIP_2024/microblaze_ip_interface/soc.srcs/sources_1/bd/soc/ip/soc_xbar_26/soc_xbar_26_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_xbar_26'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
