# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/soc/soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc || ORIG_REF_NAME==soc} -quiet] -quiet

# IP: bd/soc/ip/soc_microblaze_0_1/soc_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_microblaze_0_1 || ORIG_REF_NAME==soc_microblaze_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_mdm_1_2/soc_mdm_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_mdm_1_2 || ORIG_REF_NAME==soc_mdm_1_2} -quiet] -quiet

# IP: bd/soc/ip/soc_clk_wiz_1_2/soc_clk_wiz_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_clk_wiz_1_2 || ORIG_REF_NAME==soc_clk_wiz_1_2} -quiet] -quiet

# IP: bd/soc/ip/soc_rst_clk_wiz_1_100M_2/soc_rst_clk_wiz_1_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==soc_rst_clk_wiz_1_100M_2} -quiet] -quiet

# IP: bd/soc/ip/soc_xbar_12/soc_xbar_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xbar_12 || ORIG_REF_NAME==soc_xbar_12} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_mem_intercon_6/soc_axi_mem_intercon_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_mem_intercon_6 || ORIG_REF_NAME==soc_axi_mem_intercon_6} -quiet] -quiet

# IP: bd/soc/ip/soc_hardware_accelerator_0_6/soc_hardware_accelerator_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_hardware_accelerator_0_6 || ORIG_REF_NAME==soc_hardware_accelerator_0_6} -quiet] -quiet

# IP: bd/soc/ip/soc_xbar_26/soc_xbar_26.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xbar_26 || ORIG_REF_NAME==soc_xbar_26} -quiet] -quiet

# IP: bd/soc/ip/soc_microblaze_0_axi_periph_14/soc_microblaze_0_axi_periph_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_microblaze_0_axi_periph_14 || ORIG_REF_NAME==soc_microblaze_0_axi_periph_14} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_bram_ctrl_0_8/soc_axi_bram_ctrl_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_bram_ctrl_0_8 || ORIG_REF_NAME==soc_axi_bram_ctrl_0_8} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_bram_ctrl_0_bram_7/soc_axi_bram_ctrl_0_bram_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_bram_ctrl_0_bram_7 || ORIG_REF_NAME==soc_axi_bram_ctrl_0_bram_7} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_uartlite_0_4/soc_axi_uartlite_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_uartlite_0_4 || ORIG_REF_NAME==soc_axi_uartlite_0_4} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_intc_0_1/soc_axi_intc_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_intc_0_1 || ORIG_REF_NAME==soc_axi_intc_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_0_0/soc_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_0_0 || ORIG_REF_NAME==soc_xlconcat_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_dlmb_v10_2/soc_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_dlmb_v10_2 || ORIG_REF_NAME==soc_dlmb_v10_2} -quiet] -quiet

# IP: bd/soc/ip/soc_ilmb_v10_2/soc_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_ilmb_v10_2 || ORIG_REF_NAME==soc_ilmb_v10_2} -quiet] -quiet

# IP: bd/soc/ip/soc_dlmb_bram_if_cntlr_2/soc_dlmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==soc_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/soc/ip/soc_ilmb_bram_if_cntlr_2/soc_ilmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==soc_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/soc/ip/soc_lmb_bram_2/soc_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_lmb_bram_2 || ORIG_REF_NAME==soc_lmb_bram_2} -quiet] -quiet

# XDC: bd/soc/soc_ooc.xdc
