# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/accelerator_soc/accelerator_soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc || ORIG_REF_NAME==accelerator_soc} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_microblaze_0_0/accelerator_soc_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_microblaze_0_0 || ORIG_REF_NAME==accelerator_soc_microblaze_0_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_dlmb_v10_0/accelerator_soc_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_dlmb_v10_0 || ORIG_REF_NAME==accelerator_soc_dlmb_v10_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_ilmb_v10_0/accelerator_soc_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_ilmb_v10_0 || ORIG_REF_NAME==accelerator_soc_ilmb_v10_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_dlmb_bram_if_cntlr_0/accelerator_soc_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==accelerator_soc_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_ilmb_bram_if_cntlr_0/accelerator_soc_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==accelerator_soc_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_lmb_bram_0/accelerator_soc_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_lmb_bram_0 || ORIG_REF_NAME==accelerator_soc_lmb_bram_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_mdm_1_0/accelerator_soc_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_mdm_1_0 || ORIG_REF_NAME==accelerator_soc_mdm_1_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_clk_wiz_1_0/accelerator_soc_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_clk_wiz_1_0 || ORIG_REF_NAME==accelerator_soc_clk_wiz_1_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_rst_clk_wiz_1_100M_0/accelerator_soc_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==accelerator_soc_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_axi_bram_ctrl_0_0/accelerator_soc_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_axi_bram_ctrl_0_0 || ORIG_REF_NAME==accelerator_soc_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_axi_mem_intercon_0/accelerator_soc_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_axi_mem_intercon_0 || ORIG_REF_NAME==accelerator_soc_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_xbar_0/accelerator_soc_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_xbar_0 || ORIG_REF_NAME==accelerator_soc_xbar_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_axi_bram_ctrl_0_bram_0/accelerator_soc_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==accelerator_soc_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_hardware_acceletor_w_0_0/accelerator_soc_hardware_acceletor_w_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_hardware_acceletor_w_0_0 || ORIG_REF_NAME==accelerator_soc_hardware_acceletor_w_0_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_axi_uartlite_0_0/accelerator_soc_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_axi_uartlite_0_0 || ORIG_REF_NAME==accelerator_soc_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_microblaze_0_axi_periph_0/accelerator_soc_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_microblaze_0_axi_periph_0 || ORIG_REF_NAME==accelerator_soc_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_xbar_1/accelerator_soc_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_xbar_1 || ORIG_REF_NAME==accelerator_soc_xbar_1} -quiet] -quiet

# IP: bd/accelerator_soc/ip/accelerator_soc_axi_intc_0_0/accelerator_soc_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_soc_axi_intc_0_0 || ORIG_REF_NAME==accelerator_soc_axi_intc_0_0} -quiet] -quiet

# XDC: bd/accelerator_soc/accelerator_soc_ooc.xdc
