# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hardware_accelerator/hardware_accelerator.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_accelerator || ORIG_REF_NAME==hardware_accelerator} -quiet] -quiet

# IP: bd/hardware_accelerator/ip/hardware_accelerator_systolic_array_0_0/hardware_accelerator_systolic_array_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_accelerator_systolic_array_0_0 || ORIG_REF_NAME==hardware_accelerator_systolic_array_0_0} -quiet] -quiet

# IP: bd/hardware_accelerator/ip/hardware_accelerator_axi_slave_0_0/hardware_accelerator_axi_slave_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_accelerator_axi_slave_0_0 || ORIG_REF_NAME==hardware_accelerator_axi_slave_0_0} -quiet] -quiet

# IP: bd/hardware_accelerator/ip/hardware_accelerator_controller_0_0/hardware_accelerator_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_accelerator_controller_0_0 || ORIG_REF_NAME==hardware_accelerator_controller_0_0} -quiet] -quiet

# IP: bd/hardware_accelerator/ip/hardware_accelerator_input_mem_0_0/hardware_accelerator_input_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_accelerator_input_mem_0_0 || ORIG_REF_NAME==hardware_accelerator_input_mem_0_0} -quiet] -quiet

# IP: bd/hardware_accelerator/ip/hardware_accelerator_output_mem_0_0/hardware_accelerator_output_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_accelerator_output_mem_0_0 || ORIG_REF_NAME==hardware_accelerator_output_mem_0_0} -quiet] -quiet

# IP: bd/hardware_accelerator/ip/hardware_accelerator_vir_input_mem_0_0/hardware_accelerator_vir_input_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_accelerator_vir_input_mem_0_0 || ORIG_REF_NAME==hardware_accelerator_vir_input_mem_0_0} -quiet] -quiet

# IP: bd/hardware_accelerator/ip/hardware_accelerator_weight_mem_0_0/hardware_accelerator_weight_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_accelerator_weight_mem_0_0 || ORIG_REF_NAME==hardware_accelerator_weight_mem_0_0} -quiet] -quiet

# IP: bd/hardware_accelerator/ip/hardware_accelerator_and_gate_0_0/hardware_accelerator_and_gate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_accelerator_and_gate_0_0 || ORIG_REF_NAME==hardware_accelerator_and_gate_0_0} -quiet] -quiet

# IP: bd/hardware_accelerator/ip/hardware_accelerator_mux_0_0/hardware_accelerator_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_accelerator_mux_0_0 || ORIG_REF_NAME==hardware_accelerator_mux_0_0} -quiet] -quiet

# IP: bd/hardware_accelerator/ip/hardware_accelerator_mux_1_0/hardware_accelerator_mux_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_accelerator_mux_1_0 || ORIG_REF_NAME==hardware_accelerator_mux_1_0} -quiet] -quiet

# IP: bd/hardware_accelerator/ip/hardware_accelerator_axi_master_0_1/hardware_accelerator_axi_master_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_accelerator_axi_master_0_1 || ORIG_REF_NAME==hardware_accelerator_axi_master_0_1} -quiet] -quiet

# XDC: bd/hardware_accelerator/hardware_accelerator_ooc.xdc
