# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/vivado files/microblaze_accelerator_interface/microblaze_accelerator_interface.srcs/sources_1/bd/accelerator_soc/ip/accelerator_soc_xbar_1/accelerator_soc_xbar_1.xci
# IP: The module: 'accelerator_soc_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado files/microblaze_accelerator_interface/microblaze_accelerator_interface.srcs/sources_1/bd/accelerator_soc/ip/accelerator_soc_xbar_1/accelerator_soc_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'accelerator_soc_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/vivado files/microblaze_accelerator_interface/microblaze_accelerator_interface.srcs/sources_1/bd/accelerator_soc/ip/accelerator_soc_xbar_1/accelerator_soc_xbar_1.xci
# IP: The module: 'accelerator_soc_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado files/microblaze_accelerator_interface/microblaze_accelerator_interface.srcs/sources_1/bd/accelerator_soc/ip/accelerator_soc_xbar_1/accelerator_soc_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'accelerator_soc_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
