# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hardware_acceletor/hardware_acceletor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_acceletor || ORIG_REF_NAME==hardware_acceletor} -quiet] -quiet

# IP: bd/hardware_acceletor/ip/hardware_acceletor_axi_master_0_0/hardware_acceletor_axi_master_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_acceletor_axi_master_0_0 || ORIG_REF_NAME==hardware_acceletor_axi_master_0_0} -quiet] -quiet

# IP: bd/hardware_acceletor/ip/hardware_acceletor_axi_slave_0_0/hardware_acceletor_axi_slave_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_acceletor_axi_slave_0_0 || ORIG_REF_NAME==hardware_acceletor_axi_slave_0_0} -quiet] -quiet

# IP: bd/hardware_acceletor/ip/hardware_acceletor_controller_0_0/hardware_acceletor_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_acceletor_controller_0_0 || ORIG_REF_NAME==hardware_acceletor_controller_0_0} -quiet] -quiet

# IP: bd/hardware_acceletor/ip/hardware_acceletor_input_mem_0_0/hardware_acceletor_input_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_acceletor_input_mem_0_0 || ORIG_REF_NAME==hardware_acceletor_input_mem_0_0} -quiet] -quiet

# IP: bd/hardware_acceletor/ip/hardware_acceletor_output_mem_0_0/hardware_acceletor_output_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_acceletor_output_mem_0_0 || ORIG_REF_NAME==hardware_acceletor_output_mem_0_0} -quiet] -quiet

# IP: bd/hardware_acceletor/ip/hardware_acceletor_systolic_array_0_0/hardware_acceletor_systolic_array_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_acceletor_systolic_array_0_0 || ORIG_REF_NAME==hardware_acceletor_systolic_array_0_0} -quiet] -quiet

# IP: bd/hardware_acceletor/ip/hardware_acceletor_vir_input_mem_0_0/hardware_acceletor_vir_input_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_acceletor_vir_input_mem_0_0 || ORIG_REF_NAME==hardware_acceletor_vir_input_mem_0_0} -quiet] -quiet

# IP: bd/hardware_acceletor/ip/hardware_acceletor_weight_mem_0_0/hardware_acceletor_weight_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_acceletor_weight_mem_0_0 || ORIG_REF_NAME==hardware_acceletor_weight_mem_0_0} -quiet] -quiet

# XDC: bd/hardware_acceletor/hardware_acceletor_ooc.xdc
